[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  publish = "."
  autoLaunch = false

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "microphone=(self)"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
